### ISSUE TITLE
B2 : Incrémenation numéro ?

### ISSUE THREAD

**Issue by moustapha12** [dialibah/DPTracker#4]
B2 : A chaque fois que l’on clique sur l’onglet « création d’un chargement », un nouveau numéro doit se générer afin de pouvoir différencier les chargements.
Les numéros de chargement doivent s’incrémenter et doivent être uniques

Est ce qu'il est possible d'avoir une valeur numérique  ou alpha numérique qui s'incrémente à la place d'un GUID : 6B49011E-20BA-4FEB-BD8F-45C712352BDA

En effet il est plus facile de communiquer avec un id numérique ou alpahnumerique comme 00112 , CH000112 , ...

Si un client m'appelle pour me communiquer un id, il serait plus facile pour nous deux de se passer d un GUID.

**Comment by nureynisow** [comment]
corrigé et sera embarqué lors de la prochaine MER
