### ISSUE TITLE
B3 : Pas de message de confirmation suite au click sur le bouton Enregistrer

### ISSUE THREAD

**Issue by moustapha12** [dialibah/DPTracker#5]
B3 : Lors de la création du chargement, l’administrateur doit renseigner certaines informations :
o Le 1er champ est le numéro du chargement qui sera généré automatiquement (voir B2)
o La date de départ du chargement (proposer un petit calendrier)
o La date d’arrivée du chargement (proposer un petit calendrier)

Pour l’ergonomie Il serait préférable d'avoir un **message qui confirme** que les données ont été bien enregistrées.

Même constat sur le bouton enregistrer un colis.

**Comment by nureynisow** [comment]
Fait et livré lors de la prochaine MER
