### ISSUE TITLE
B3 : Données obligatoires

### ISSUE THREAD

**Issue by moustapha12** [dialibah/DPTracker#6]
B3 : Lors de la création du chargement, l’administrateur doit renseigner certaines informations :
o Le 1er champ est le numéro du chargement qui sera généré automatiquement (voir B2)
o La date de départ du chargement (proposer un petit calendrier)
o La date d’arrivée du chargement (proposer un petit calendrier)

Je pense qu'il faudra que certaines informations soient **obligatoires** comme la description. 
Et peut être pour la date de départ prévisionnelle du chargement

**Comment by nureynisow** [comment]
Fait et sera livré lors de la MER
