### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by moustapha12** [dialibah/DPTracker#7]
[Recette_DP_Tracker_Authentification.pdf](https://github.com/dialibah/DPTracker/files/1587712/Recette_DP_Tracker_Authentification.pdf)
- Si  je m'enregistre avec un compte qui existe déjà, il semble que le message n'est pas adapté.
Il me dit que **ce n'est pas le même mot de passe** alors qu'il devrait dire que "**le compte existe déjà**".

- il faut traduire le message 'Not same pwd' si les mots de passe ne sont pas identique à l'enregistrement

- il faut pouvoir récupérer son mot passe (Fonctionnalité non présente cependant dans le cahier des charges)

**Comment by nureynisow** [comment]
Sera livré lors de la prochaine MER
