### ISSUE TITLE
B4 : Le chargement créé doit avoir 2 options :

### ISSUE THREAD

**Issue by moustapha12** [dialibah/DPTracker#8]
1- Les statuts archivé n'est pas adapté à ce niveau. il ne doit erte possible qu'une fois le chargement est cloturé. 
 

2- Impossible d'enregistrer le statut d'un chargement. J ouvre le chargement puis je modifie le statut en le faisant passer de Créé à Ouvert. La modification n'est pas prise en compte  en cliquant sur Enregsitrer si  les deux dates ne sont pas saisies. Il faut prévoir un message  pour informer l'utilisateur des données obligatoires à saisir pour valider l 'enregistrement

3 - A ce stade on ne voit pas le bouton Clotûter.  Peut être est ce trop tôt.

4 - SI on affiche la liste des chargement avec le bouton Chargement  le statut est en anglais Create ou open aulieu de créé ou ouvert.

5 - Le statut est Fermé ou lieu de Cloturé et le statut En cours au lieu de En route

**Comment by nureynisow** [comment]
fixed
